import 'package:isar/isar.dart';

part 'anagrafica.g.dart';

@collection
@Name("Anagrafica")
class Anagrafica {
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  String? codiceFiscale; // Colonna C (2)

  String? cid; // Colonna A (0)
  String? nominativo; // Colonna B (1)
  String? sesso; // Colonna D (3)
  String? dataNascita; // Colonna E (4)
  String? luogoNascita; // Colonna F (5)
  String? dataAssunzione; // Colonna G (6)
  String? dataAssunzioneGruppo; // Colonna H (7)
  String? tipoScuola; // Colonna I (8)
  String? formazione; // Colonna J (9)
  String? livello; // Colonna K (10)
  String? tipoDip; // Colonna L (11)
  String? gradoOccupaz; // Colonna M (12)
  String? gradoOccupazInSol; // Colonna N (13)
  String? contrSolidarieta; // Colonna O (14)
  String? societa; // Colonna P (15)
  String? societaContabile; // Colonna Q (16)
  String? unitaOrg3; // Colonna R (17)
  String? unitaOrg3Des; // Colonna S (18)
  String? unitaOrg4; // Colonna T (19)
  String? unitaOrg4Des; // Colonna U (20)
  String? unitaOrg5; // Colonna V (21)
  String? unitaOrg5Des; // Colonna W (22)
  String? unitaOrg6; // Colonna X (23)
  String? unitaOrg6Des; // Colonna Y (24)
  String? unitaOrg7; // Colonna Z (25)
  String? unitaOrg7Des; // Colonna AA (26)
  String? unitaOrg8; // Colonna AB (27)
  String? unitaOrg8Des; // Colonna AC (28)
  String? unitaOrg9; // Colonna AD (29)
  String? unitaOrg9Des; // Colonna AE (30)
  String? unitaOrganizzativa; // Colonna AF (31)
  String? cidResponsabileUO; // Colonna AG (32)
  String? nominativoResponsabileUO; // Colonna AH (33)
  String? mailResponsabileUO; // Colonna AI (34)
  String? paese; // Colonna AJ (35)
  String? regione; // Colonna AK (36)
  String? provincia; // Colonna AL (37)
  String? sedeProvincia; // Colonna AM (38)
  String? sedeIndirizzo; // Colonna AN (39)
  String? sedeCap; // Colonna AO (40)
  String? sedeComune; // Colonna AP (41)
  String? tipoContratto; // Colonna AQ (42)
  String? partTimeFullTime; // Colonna AR (43)
  String? mansione; // Colonna AS (44)
  String? posizione; // Colonna AT (45)
  String? nuovoSistProfFamiglia; // Colonna AU (46)
  String? nuovoSistProfArea; // Colonna AV (47)
  String? nuovoSistProfAmbito; // Colonna AW (48)
  String? nuovoSistProfJob; // Colonna AX (49)
  String? status; // Colonna AY (50)
  String? utenteCOD; // Colonna AZ (51)
  String? utenteRU; // Colonna BA (52)
  String? utenteKA; // Colonna BB (53)
  String? utenteRUBU; // Colonna BC (54)
  String? indirizzoMail; // Colonna BD (55)
  String? cidKeyAccount; // Colonna BE (56)
  String? nominativoKeyAccount; // Colonna BF (57)
  String? mailKeyAccount; // Colonna BG (58)
  String? cidGestore; // Colonna BH (59)
  String? nominativoGestore; // Colonna BI (60)
  String? mailGestore; // Colonna BJ (61)
  String? under35; // Colonna BK (62)
  String? responsabileSINO; // Colonna BL (63)
  String? tipologiaResponsabile; // Colonna BM (64)
  String? matricolaAziendaleUID; // Colonna BN (65)

  DateTime? lastUpdate;
  String? importBatch; // Codice univoco dell'import
}
